apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 2
  templates:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: Blackbirddev/demoapp
      #  resources:
        #  limits:
          #  memory: "128Mi"
          #  cpu: "500m"
        ports:
        - containerPort: 80
