apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfrontend
spec:
  replicas: 1
  selector:
      app: webfrontend
  template:
    metadata:
      labels:
        app: webfrontend
    spec:
      containers:
      - name: webfrontend
        image: blackbirddev.azurecr.io/webfrontend:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: {{ .Values.title }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: webfrontend-{{.Release.Name}}
