apiVersion: v1
kind: Service
metadata:
  labels:
    app: sampleapp
  name: sampleapp-nodeport-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    app: sampleapp
  type: NodePort
