apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    #nodePort: 31000
  selector:
    app: myapp
  type: LoadBalancer
