apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp
  name: demoapp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    #nodePort: 31000
  selector:
    app: demoapp
  type: LoadBalancer
