on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
            
       # - name: 'Setup Kubectl'
          #uses: azure/Setup-login@v1
          
        - name: 'Kubernetes Set context'
          uses: azure/k8s-set-context@v2
          with:
            kubeconfig: ${{secrets.KUBE_CONFIG}}
        - run: |
            kubectl run sampleapp --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }} -o yaml --dry-run|kubectl -n blackbird-aks -f -
            kubectl -n blackbird-aks expose deploy sampleapp --port 80 --type LoadBalancer -o yaml --dry-run json|kubectl -n blackbird-aks -f -
          
          


