name: AUTO DEPLOY CONTAINER

  #env:
 
 
 
 
 
 #ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  #ARM_TENANT_ID:  ${{ secrets.TENANT_ID }}
  
 # DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  #USERNAME: Docker
  #REPOSITORY_NAME: Docker Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1
        with:
    # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
         creds: ${{env.AZURE_CREDENTIALS}}
         
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
    # Specify the script here
         inlineScript: az login --service-principal --Subscription ${{ secrets.AZURE_CREDENTIALS }} --tenant ${{ secrets.ARM_TENANT_ID }} --password certificate.pem
    # Azure CLI version to be used to execute the script. If not provided, latest version is used
       # azcliversion: # optional, default is agentazcliversion
      - name: Install Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        run: docker login --username=yourhubusername --password=$DOCKER_HUB_PASSWORD
      - name: Build Image
        run: docker build -t $USERNAME/$REPOSITORY_NAME:$IMAGE_TAG .
      - name: Push Image
        run: docker push $USERNAME/$REPOSITORY_NAME:$IMAGE_TAG
