name: Linux_Container_Workflow
on:
  push:
    branches:
    - Naveen

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/webfrontend:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/webfrontend:${{ github.sha }}
            
      
          
        - name: 'aks Set context'
          uses: azure/aks-set-context@v1
          with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
             cluster-name: ${{ secrets.CLUSTER_NAME }}
             resource-group: ${{ secrets.RESOURCE_GROUP }}
             #kubeconfig: ${{secrets.KUBE_CONFIG}}
            
       
        - name: 'Helm tool installer'
          uses: Azure/setup-helm@v1
          with:
           version: v3.3.1
           
        - name: 'create pull secret' 
          uses: azure/k8s-create-secret@v1
          with:
           container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io
           container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
           container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
           secret-name: ${{ secrets.REGISTRY_LOGIN_SERVER }}-registry-connection   
          
       
          
             
        - name: 'Helm Bake'
          uses: azure/k8s-bake@v1
          with:
           #renderEngine: 'helm2'
           #helmChart: ./deploy helm/
           #overrideFiles: './deploy helm/values.yaml'
           #overrides: |     
            #replicas:2
            #helm-version: 'latest' 
            #id: bakec
           renderEngine: 'helm2'
           helmChart: './deploy helm/' 
           overrideFiles: './deploy helm/values-override.yaml'
           overrides: |     
                replicas:2
                helm-version: 'latest' 
                silent: 'false'

     
       #- name: 'Deploy app to AKS'
        #  uses: azure/k8s-deploy@v1
          #with:
            ##images: |
            # ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io/webfrontend:${{ github.sha }}
            #imagepullsecrets: |
             #${{ secrets.REGISTRY_LOGIN_SERVER}}-registry-connection
            #action: deploy
  
       
       
          #imagepullsecrets: |
           # ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #  namespace: ${{ env.NAMESPACE }}
      # ${{ steps.bake.outputs.manifestsBundle }}
        

 # - name: 'Setup Kubectl"
          #uses: azure/Setup-login@v1
